# Generated by Django 2.1.5 on 2019-12-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetentry',
            name='amount_spent',
        ),
        migrations.AddField(
            model_name='expense',
            name='payments',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expense',
            name='paymeny_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cash'), (2, 'Visa'), (3, 'Visa CAL'), (4, 'Diners')], default=1),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.CharField(default='ariel', max_length=200),
        ),
    ]
