# Generated by Django 2.1.5 on 2019-12-06 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20191204_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetentry',
            name='budget_cycle',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Month'), (2, 'Year'), (3, 'Week')], default=1),
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date end'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetentry',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date start'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paymeny_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cash'), (2, 'Visa'), (3, 'Visa CAL'), (4, 'Diners')], default=2),
        ),
    ]
