# Generated by Django 2.1.5 on 2019-12-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20191206_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='paymeny_method',
            new_name='payment_method',
        ),
    ]
