# Generated by Django 2.1.5 on 2019-12-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20191206_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetentry',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
